Developer
novikovdeveloper/Sprint_4 pull request #2
Opened 2023-06-06 15:18 UTC by novikovdeveloper

2023-06-06 21:44 UTC, kadirovgm requested changes

2023-06-06 21:44 UTC, kadirovgm commented on .idea/Sprint_4.iml
нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

2023-06-06 21:44 UTC, kadirovgm commented on .idea/inspectionProfiles/profiles_settings.xml
нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

2023-06-06 21:44 UTC, kadirovgm commented on .idea/modules.xml
нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

2023-06-06 21:44 UTC, kadirovgm commented on .idea/misc.xml
нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

2023-06-06 21:44 UTC, kadirovgm commented on .idea/vcs.xml
нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

2023-06-06 21:44 UTC, kadirovgm commented on page_object/main_page.py
> +class MainPage:
Нужно исправить: MainPage должен наследовать BasePage - в этом и есть смысл в нем хранить общие методы

2023-06-06 21:44 UTC, kadirovgm commented on page_object/main_page.py
> +    def __init__(self, driver):
Нужно исправить: после наследования BasePage не будет необходимости init, так как это уже сделано в базовом классе

2023-06-06 21:44 UTC, kadirovgm commented on conftest.py
> +
отлично!

2023-06-06 21:44 UTC, kadirovgm commented on page_object/base_page.py
> +    def click_on_upper_order_button(self):
Нужно исправить: это не общий метод, а метод конкретной страницы, он не должен храниться в BasePage

2023-06-06 21:44 UTC, kadirovgm commented on page_object/base_page.py
> +    def click_on_down_order_button(self):
Нужно исправить: это не общий метод, а метод конкретной страницы, он не должен храниться в BasePage

2023-06-06 21:44 UTC, kadirovgm commented on page_object/base_page.py
> +    def wait_for_loading_dzen_page(self):
Нужно исправить: это не общий метод, а метод конкретной страницы, он не должен храниться в BasePage

Общим методом бы он стал, если бы умел ожидать загрузку любой страницы, а не только конкретно дзена

2023-06-06 21:44 UTC, kadirovgm commented on page_object/main_page.py
> +    def click_on_first_question(self):
Нужно исправить: в прошлый раз уже писал, что эти методы нужно объединить в одну, перечитай те комменты плиз

2023-06-06 21:44 UTC, kadirovgm commented on page_object/order_page.py
> +class OrderPage:
Нужно исправить: наследовать BasePage

2023-06-06 21:44 UTC, kadirovgm commented on tests/test_accordion.py
> +        assert main_page.get_first_answer_text() == 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
нужно исправить: тестовые данные вынести в отдельный файл

2023-06-07 09:03 UTC, novikovdeveloper commented on .idea/Sprint_4.iml
Привет! Создал новую ветку, так как развернул проект на другой машине, и в той же ветке не получается работать

2023-06-07 10:30 UTC, novikovdeveloper commented on tests/test_accordion.py
> +        assert main_page.get_first_answer_text() == 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
не понимаю как реализовать параметризованный тест не переписывая весь код с нуля

2023-06-07 10:31 UTC, novikovdeveloper commented on tests/test_accordion.py
> +        assert main_page.get_first_answer_text() == 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
> нужно исправить: тестовые данные вынести в отдельный файл

не понимаю как реализовать параметризованный тест не переписывая весь код с нуля

2023-06-07 10:32 UTC, novikovdeveloper commented on .idea/Sprint_4.iml
> нужно исправить: этот файл не относится к проекту, надо удалить либо поместить в гитигнор

Привет! Создал новую ветку, так как развернул проект на другой машине, и в той же ветке не получается работать

2023-06-07 20:23 UTC, kadirovgm commented on tests/test_accordion.py
> +        assert main_page.get_first_answer_text() == 'Сутки — 400 рублей. Оплата курьеру — наличными или картой.'
нет, я же не прошу создать параметризацию, тут дело в том, что вот эти ожидаемые текста ответов можно поместить в отдельный файл и отдельный класс Answers() например, тогда можно переменные этого класса использовать как ожидаемое значение. Просто в масштабных проектах так и делают, так как этими тестовыми данными могут пользоваться множество тестов, тогда получается удобнее поддерживать изменения в тестах

2023-06-07 20:30 UTC, kadirovgm approved these changes

2023-06-07 20:30 UTC, kadirovgm commented on helpers.py
> +
отлично!

2023-06-07 20:30 UTC, kadirovgm commented on pages/base_page.py
> +
да, типа того, с масштабированием проектов будут появляться множество общих методов для страницы, которых нужно будет помещаться сюда. Просто хотелось чтобы ты понял этот принцип и пользовался на реальных проектах

2023-06-07 20:30 UTC, kadirovgm commented on pages/main_page.py
> +    def wait_for_load_enter_button(self):
Можно лучше: можно было сделать общим методом: wait_for_load(self, locator) - и переместить в BasePage

2023-06-07 20:30 UTC, kadirovgm commented on pages/main_page.py
> +    def wait_for_load_header_main_questions(self):
Можно лучше: можно было сделать общим методом, ато получается у тебя два почти одинаковых метода для ожидания загрузки - это не хорошо

2023-06-23 16:40 UTC, merged